- arguments: [--ignore-glob=bugs/GxlDtd.hs]
- ignore: {name: Use camelCase}
- ignore: {name: Use first}
- ignore: {name: Use second}
- ignore: {name: Use null}
- ignore: {name: Use record patterns}
- ignore: {name: Use newtype instead of data}
- ignore: {name: Use lambda-case}
- ignore: {name: Eta reduce}
- ignore: {name: Use head}
- ignore: {name: Use print}
- ignore: {name: Redundant flip}
- ignore: {name: Use fmap, within: Text.XML.HaXml.TypesQC}
