name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['9.4', '9.2', '9.0', '8.10', '8.8', '8.6', '8.4', '8.2', '8.0']
        include:
          ghc: 9.6.0.20230111
          ghcup_release_channel: "https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-prereleases-0.0.7.yaml"
    name: Haskell GHC ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          ghcup-release-channel: ${{ matrix.ghcup_release_channel }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cabal
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal','**/cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
            ${{ runner.os }}-
      - run: cabal update
      - run: cabal build
      - run: cabal haddock
      - run: cabal check
      - run: cabal sdist
